#
# Any settings added to this file will be available in Kit#config.
#
#
# Database configuration loaded by ActiveRecord.
# Settings shown for an sqlite adapter.
:db:
  :adapter: sqlite3
  :database: db/kit.sqlite